name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Read .nvmrc
        shell: /bin/bash -l {0}
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.1

      - name: Install dependencies
        shell: /bin/bash -l {0}
        run: pnpm install --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Release
        uses: changesets/action@v1
        with:
          setupGitUser: false
          version: pnpm release:version
          publish: pnpm release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.MY_TOKEN }}
